package java8;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

public class MapAndFlatMap {
    public static void main(String[] args) {
        List<String> loseWeight = new ArrayList<>();
        loseWeight.add("avocados");
        loseWeight.add("beans");
        loseWeight.add("salad");
        loseWeight.add("oats");
        loseWeight.add("broccoli");

        System.out.println("list of String : " + loseWeight);

        List<Integer> listOfInts = loseWeight.stream().map(String::length).collect(Collectors.toList());
        System.out.println("list of ints generate by map(): " + listOfInts);

        List<List> listOfListOfNumber = new ArrayList<>();

        listOfListOfNumber.add(Arrays.asList(2, 4));
        listOfListOfNumber.add(Arrays.asList(3, 9));
        listOfListOfNumber.add(Arrays.asList(4, 16));

        System.out.println("list of list : " + listOfListOfNumber);  //
        Object listOfIntegers = listOfListOfNumber.stream().flatMap(list -> list.stream()).collect(Collectors.toList());

        System.out.println("list of numbers generated by flatMap : " + listOfIntegers);


    }
}
